---
- hosts: all
  gather_facts: no
  become: true
  vars_files:
    - ../vars.yml
  tasks:

    - name: Installing ntpdate
      yum:
        name: ntpdate
        state: latest

    - name: Updating time
      shell: "ntpdate -u a.ntp.br"

    - name: Saving time into hardware
      shell: "hwclock -w"

