---
- hosts: all
  gather_facts: no
  become: true
  tasks:

    - name: Installing epel-release
      yum:
        name: epel-release
        state: latest

    - name: Installing terminal programs
      shell: "yum install -y net-tools pciutils ntfs-3g vim ntpdate ntsysv xarchiver wget mousepad vsftpd wine gcc
      ImageMagick iotop dstat lm_sensors make elinks bind telnet unzip mlocate"

    - name: Disable PC Beep
      lineinfile:
        dest: "/etc/modprobe.d/nobeep.conf"
        state: present
        create: yes
        line: "blacklist pcspkr"
